"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var product_controller_1 = require("../controllers/product.controller");
var location_controller_1 = require("../controllers/location.controller");
var express = require('express');
var router = express.Router();
router.get("/locate", location_controller_1.getBunks);
router.post("/locate", product_controller_1.getProductsByLocation);
router.post("/bunk", location_controller_1.getBunkBySku);
module.exports = router;
